export const PROJECTS = [
  {
    id: "01",
    name: "OLO",
    title: "Olo",
    slug: "olocasestudy",
    tags: ["EMOTIONAL DESIGN", "UX", "UI"],
    role: "Product Designer",
    bgColor: "#000000",
    textColor: "#FFFFFF",
    img: "/olo.webp",
    cta: "Turning small hellos into meaningful growth through introverted design.",
    cursorCta: "Discover introverted design",
    link: "/casestudies/olo/index.html"
  },
  {
    id: "05",
    name: "Redesigning Orco",
    title: "Redesigning Orco",
    slug: "orco",
    tags: ["UX DESIGN", "WEB DESIGN", "BRANDING"],
    role: "UX Designer & Strategist",
    bgColor: "#000000",
    textColor: "#FFFFFF",
    img: "/orco.mp4",
    cta: "Transforming a heritage Italian food brand into an interactive culinary experience.",
    cursorCta: "Explore the culinary experience",
    link: "/casestudies/orco/orco-case-study.html"
  },
  {
    id: "04",
    name: "MICA",
    title: "MICA",
    slug: "mica",
    tags: ["UX DESIGN", "CO-LIVING DESIGN"],
    role: "Lead UX Designer",
    bgColor: "#000000",
    textColor: "#FFFFFF",
    img: "/mica.mp4", 
    objectPosition: "left",
    cta: "Designing belonging through emotionally intelligent housing experiences.",
    cursorCta: "See how I designed belonging",
    link: "/casestudies/mica/index.html"
  },
  {
    id: "02",
    name: "KRIZIA",
    title: "Krizia",
    slug: "krizia",
    tags: ["WEB DESIGN", "UX", "ART DIRECTION"],
    role: "Brand & Digital Designer",
    bgColor: "#000000",
    textColor: "#FFFFFF",
    img: "/krizia.mp4",
    cta: "Rebranding Luxury Through Structure",
    cursorCta: "See how I visualised luxury",
    link: "/casestudies/krizia/index.html"
  },
  {
    id: "03",
    name: "ELI5",
    title: "ELI5",
    slug: "eli5",
    tags: ["UX DESIGN", "INTERACTION & UX SYSTEMS"],
    role: "UX Researcher & Designer",
    bgColor: "#000000",
    textColor: "#FFFFFF",
    img: "/works/media__1777587436505.webp",
    cta: "Transforms complexity into visual clarity instantly.",
    cursorCta: "See the visual clarity process",
    link: "/casestudies/eli5/index.html"
  }
];
